from sqlalchemy.orm import Session

from ..services import market_service
from .base import Candle, MarketDataAdapter


class DummyMarketDataAdapter(MarketDataAdapter):
    """Serves this app's own simulated price history (PriceData rows generated by
    market_service's random-walk/trending/volatile/sideways models)."""

    def __init__(self, db: Session):
        self.db = db

    def get_historical_candles(self, symbol: str, limit: int | None = None) -> list[Candle]:
        rows = market_service.get_prices(self.db, symbol, limit)
        return [
            Candle(date=r.timestamp.date(), open=r.open, high=r.high, low=r.low, close=r.close, volume=r.volume)
            for r in rows
        ]

    def get_latest_price(self, symbol: str) -> float | None:
        candles = self.get_historical_candles(symbol, limit=1)
        return candles[-1].close if candles else None
