from sqlalchemy.orm import Session

from ..services import market_service
from .base import Candle, MarketDataAdapter


class DummyMarketDataAdapter(MarketDataAdapter):
    """Serves this app's own price history (PriceData rows: generated by market_service's
    random-walk/trending/volatile/sideways models, or imported from real data).

    By default it only returns candles up to the market clock, which is what live strategies
    and auto-trading should see. `full_history=True` returns every stored candle regardless --
    for backtests, which analyse the whole series."""

    def __init__(self, db: Session, full_history: bool = False):
        self.db = db
        self.full_history = full_history

    def get_historical_candles(self, symbol: str, limit: int | None = None) -> list[Candle]:
        rows = market_service.get_prices(self.db, symbol, limit, full=self.full_history)
        return [
            Candle(date=r.timestamp.date(), open=r.open, high=r.high, low=r.low, close=r.close, volume=r.volume)
            for r in rows
        ]

    def get_latest_price(self, symbol: str) -> float | None:
        candles = self.get_historical_candles(symbol, limit=1)
        return candles[-1].close if candles else None
